In [1]:
import numpy as np

In [2]:
list = [1,2,3,4]

In [5]:
a=np.array(list)
a

array([1, 2, 3, 4])

In [6]:
a.copy()

array([1, 2, 3, 4])

In [7]:
np.random.rand(2,3)

array([[0.1658    , 0.4693749 , 0.33352523],
       [0.71838027, 0.05975046, 0.30647059]])

In [14]:
a=np.random.randint(34,54,size=(3,5))
a

array([[34, 36, 36, 47, 53],
       [50, 40, 36, 36, 53],
       [38, 40, 43, 37, 42]])

In [16]:
a[1,3]

36

In [17]:
a.reshape(5,3)

array([[34, 36, 36],
       [47, 53, 50],
       [40, 36, 36],
       [53, 38, 40],
       [43, 37, 42]])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
b=np.ones((4,5,3))

In [30]:
b[1,2,2]
b

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [31]:
b[1]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
c=np.random.randint(0,100,size=(6,6,6))
c

array([[[91, 51, 97,  3, 53, 26],
        [22, 53, 16, 87, 14, 19],
        [98,  8, 70, 90, 22, 70],
        [45, 80, 83, 33, 37, 53],
        [71, 24, 27, 86,  2, 50],
        [98,  7, 87, 55, 24, 26]],

       [[ 9,  8,  5, 85, 37, 26],
        [95, 61,  2, 79, 58, 25],
        [18, 67,  9, 12, 90, 40],
        [73, 27, 29,  0, 79, 83],
        [43, 63, 79, 32, 28, 78],
        [17, 56, 18, 10, 83, 58]],

       [[69, 23, 85, 94, 20, 57],
        [52, 55, 81, 34, 14, 60],
        [30, 55, 34, 51, 21, 66],
        [86, 52, 84, 93,  8, 52],
        [32, 89, 13, 58, 82, 87],
        [78, 43, 47, 81, 93, 50]],

       [[38, 78, 27, 23, 94, 13],
        [51, 85, 41, 53,  3, 86],
        [10, 12, 12,  5, 93, 84],
        [69, 50, 13, 63, 74, 73],
        [79, 41, 86, 95, 25, 66],
        [84, 59, 34,  7, 48, 76]],

       [[45, 21,  8,  7, 32, 31],
        [69, 44, 26, 94, 14, 77],
        [69, 31, 87,  3, 67, 85],
        [51, 48, 61,  9, 58, 19],
        [11, 80,  1,  6, 35, 97],
      

In [35]:
c[1,1:5:2,1]

array([61, 27])

In [36]:
c[1,1:5:2]

array([[95, 61,  2, 79, 58, 25],
       [73, 27, 29,  0, 79, 83]])

In [39]:
np.min(c[1,1:5:2], axis=0)

array([73, 27,  2,  0, 58, 25])

In [40]:
# axis=1 row
# axis=0 col

In [41]:
np.sum(c)

11002

In [43]:
np.sin(a)

array([[ 0.52908269, -0.99177885, -0.99177885,  0.12357312,  0.39592515],
       [-0.26237485,  0.74511316, -0.99177885, -0.99177885,  0.39592515],
       [ 0.29636858,  0.74511316, -0.83177474, -0.64353813, -0.91652155]])

In [44]:
a+a

array([[ 68,  72,  72,  94, 106],
       [100,  80,  72,  72, 106],
       [ 76,  80,  86,  74,  84]])

In [45]:
a**2

array([[1156, 1296, 1296, 2209, 2809],
       [2500, 1600, 1296, 1296, 2809],
       [1444, 1600, 1849, 1369, 1764]])

In [46]:
c.shape

(6, 6, 6)

In [47]:
c.size

216

In [48]:
c.itemsize

8

In [49]:
c.dtype

dtype('int64')

In [50]:
c.ndim

3

In [51]:
import pandas as pd

In [53]:
df = pd.DataFrame(columns=[]);

In [54]:
df.columns

Index([], dtype='object')

In [55]:
# pd.read_excel("", del)

In [57]:
# df['name'][1:2]

In [58]:
# df.iloc[2:3,23]

In [59]:
# df.loc[df['mae']==s]

In [60]:
# df.drop(columns=[''])

In [61]:
# df.head(3) 

In [63]:
# df.apply(lambda x: )
# df.describe()

In [64]:
# df.unique()
# df.isna()

In [65]:
# df.to_csv()

In [68]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [69]:
# value_counts
# corr()

In [72]:
# import seaborn as sns
# sns.get_dataset_names()
# sns.load_dataset()
# sns.scatterplot(x,y,hue, kde, kind, size, row, col, data)
# sns.heatmap(matrix)
# sns.histplot()
# sns.lineplot
# sns.pairplot
# lmplot