In [1]:
# NumPy --> Numerical Python
# It is contiguous memory

In [2]:
import numpy as np

In [3]:
list = [1,2,3,4];

In [4]:
a = np.array(list)

In [5]:
print(a)

[1 2 3 4]


In [6]:
# b = np.array([[1,2,3,4],[2,2,34,5]])
b = np.array([[1,2,3,4],[2,2,34,5]], dtype="int16")

In [7]:
print(b)

[[ 1  2  3  4]
 [ 2  2 34  5]]


In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [10]:
a.shape

(4,)

In [11]:
b.shape

(2, 4)

In [12]:
a.dtype

dtype('int32')

In [13]:
b.dtype

dtype('int16')

In [14]:
a.itemsize

4

In [15]:
b.itemsize

2

In [16]:
a.size * a.itemsize

16

In [17]:
b.size * b.itemsize

16

In [18]:
c = np.array([[1,2,3,4,5,6,7],[7,6,5,4,3,2,1]])

In [19]:
c[1, 5]

2

In [20]:
c[0, 5]

6

In [21]:
print(c[1,:])

[7 6 5 4 3 2 1]


In [22]:
c[:,2]

array([3, 5])

In [23]:
c[1,0::2]

array([7, 5, 3, 1])

In [24]:
c[1,4] = 20

In [25]:
c[:,6] = 5

In [26]:
c[:,5] = -1

In [27]:
c

array([[ 1,  2,  3,  4,  5, -1,  5],
       [ 7,  6,  5,  4, 20, -1,  5]])

In [28]:
d = np.array([[[1,2],[3,4]],[[4,5],[6,7]]])

In [29]:
d

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [30]:
d[0,1,1]

4

In [31]:
d[:,1,:]

array([[3, 4],
       [6, 7]])

In [32]:
d[1,1,1]

7

In [33]:
d[1,1,1] = 9988

In [34]:
d

array([[[   1,    2],
        [   3,    4]],

       [[   4,    5],
        [   6, 9988]]])

In [35]:
# startindex:endindex:stepsize

In [36]:
a=[1,2,4,5,6,3,4,2,1,1,1,1,1,1]

In [37]:
a[1:8:2]

[2, 5, 3, 2]

In [38]:
a=np.zeros(5)

In [39]:
print(a)

[0. 0. 0. 0. 0.]


In [40]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [41]:
np.ones((2,5,3), dtype="int16")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [42]:
np.full((2,5),99, dtype="float")

array([[99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.]])

In [43]:
np.random.rand(3,2,2)

array([[[0.2643846 , 0.27323941],
        [0.48825553, 0.2131186 ]],

       [[0.31752519, 0.28431464],
        [0.64621926, 0.61703037]],

       [[0.21821851, 0.52975079],
        [0.15983158, 0.1554285 ]]])

In [44]:
np.random.randint(23,56, size=(2,5))

array([[32, 28, 38, 47, 44],
       [39, 55, 43, 42, 55]])

In [45]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
 arr = np.ones((5,5))

In [47]:
arr[1:-1,1:-1] = np.zeros((3,3))

In [48]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
arr[2,2] = 9

In [50]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
# startindex:endindex ---> endindex is excluded

In [52]:
a=np.array([1,2,4,32,4])

In [53]:
a

array([ 1,  2,  4, 32,  4])

In [54]:
b=a

In [55]:
b

array([ 1,  2,  4, 32,  4])

In [56]:
b[3] = 201

In [57]:
b

array([  1,   2,   4, 201,   4])

In [58]:
a

array([  1,   2,   4, 201,   4])

In [59]:
# Hence b is referring to a

In [60]:
b = a.copy()

In [61]:
b

array([  1,   2,   4, 201,   4])

In [62]:
b[3]=1

In [63]:
b

array([1, 2, 4, 1, 4])

In [64]:
a

array([  1,   2,   4, 201,   4])

In [65]:
a+2

array([  3,   4,   6, 203,   6])

In [66]:
a*5

array([   5,   10,   20, 1005,   20])

In [67]:
a/54

array([0.01851852, 0.03703704, 0.07407407, 3.72222222, 0.07407407])

In [68]:
a*108

array([  108,   216,   432, 21708,   432])

In [69]:
a+b

array([  2,   4,   8, 202,   8])

In [70]:
a**2

array([    1,     4,    16, 40401,    16])

In [71]:
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.65364362,  0.99808296, -0.65364362])

In [72]:
a*b

array([  1,   4,  16, 201,  16])

In [73]:
# element wise stuff

In [74]:
a = np.ones((2,3))
b = np.ones((3,2))

In [75]:
np.matmul(a,b)

array([[3., 3.],
       [3., 3.]])

In [76]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [77]:
# Mathematics, linear algebra, statistics
a = np.array([[1,2,11,4],[5,6,7,8]])

In [78]:
np.min(a)

1

In [79]:
np.max(a)

11

In [80]:
# axis = 1 --> row
# axis = 0 --> column

In [81]:
np.min(a, axis=1)

array([1, 5])

In [82]:
np.max(a, axis=0)

array([ 5,  6, 11,  8])

In [83]:
np.sum(a)

44

In [84]:
np.sum(a, axis = 0)

array([ 6,  8, 18, 12])

In [85]:
np.sum(a, axis =1)

array([18, 26])

In [86]:
a = a.reshape((1,8))

In [87]:
a.reshape((2,2,2))

array([[[ 1,  2],
        [11,  4]],

       [[ 5,  6],
        [ 7,  8]]])

In [88]:
a=np.zeros((3,2));
b=np.ones((3,2));

np.vstack([a,b])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [89]:
np.hstack((a,b))

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [90]:
a,b

(array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [91]:
filedata = np.genfromtxt('data.txt', delimiter=",")
print(filedata)

[[  1.   2.   3.   5.   6.]
 [  2.   3.  45.  32.  13.]
 [  2.  43.  21. 323.  21.]
 [ 43. 213. 222. 443. 333.]]


In [92]:
filedata.astype('int32')

array([[  1,   2,   3,   5,   6],
       [  2,   3,  45,  32,  13],
       [  2,  43,  21, 323,  21],
       [ 43, 213, 222, 443, 333]])

In [93]:
filedata>40

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False,  True, False,  True, False],
       [ True,  True,  True,  True,  True]])

In [94]:
filedata[filedata>40]

array([ 45.,  43., 323.,  43., 213., 222., 443., 333.])

In [95]:
filedata[[1,3]]

array([[  2.,   3.,  45.,  32.,  13.],
       [ 43., 213., 222., 443., 333.]])

In [96]:
np.any(filedata>50, axis=0)

array([False,  True,  True,  True,  True])

In [97]:
np.all(filedata>50, axis=0)

array([False, False, False, False, False])

In [98]:
((filedata>50) & (filedata<500))

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False,  True,  True,  True,  True]])

In [99]:
a = np.random.randint(1,100,size=(6,5))

In [100]:
a

array([[ 8, 50, 77, 58, 53],
       [46, 90, 67, 51, 74],
       [92, 61, 62, 59, 74],
       [16, 66, 56, 77, 47],
       [11, 46, 31, 63, 37],
       [73, 63, 66, 95, 79]])

In [101]:
a[2:4,0:2]

array([[92, 61],
       [16, 66]])

In [102]:
row = np.array([0,1,2,3])

In [103]:
a[row, row+1]

array([50, 67, 59, 47])

In [104]:
a[[0,-2,-1],3:5]

array([[58, 53],
       [63, 37],
       [95, 79]])