In [37]:
from torch import tensor

In [6]:
t1 = tensor(4.)
t1

tensor(4.)

In [7]:
t1.dtype

torch.float32

In [8]:
t2 = tensor([1.,3,2,4])
t2

tensor([1., 3., 2., 4.])

In [10]:
t2.ndim

1

In [15]:
t3 = tensor([[[1,2,3,4]],[[1,5,6,7]]])
t3.shape

torch.Size([2, 1, 4])

In [22]:
x = tensor(3.)
y = tensor(4., requires_grad=True)
z = tensor(5., requires_grad=True)

In [23]:
q = x*y+z
q

tensor(17., grad_fn=<AddBackward0>)

In [24]:
der = q.backward()
der

In [25]:
der

In [27]:
x.grad

In [31]:
y.grad 
# differentitate q wrt y = x

tensor(3.)

In [32]:
z.grad
# differentitate q wrt z = 1

tensor(1.)

In [33]:
import numpy as np

In [45]:
a=np.random.randint(12,34,size=(3,5))
a

array([[23, 26, 23, 33, 33],
       [14, 30, 12, 20, 28],
       [12, 15, 22, 27, 23]])

In [46]:
import torch

In [47]:
torch.from_numpy(a) 

tensor([[23, 26, 23, 33, 33],
        [14, 30, 12, 20, 28],
        [12, 15, 22, 27, 23]])

In [49]:
tensor(a).numpy()

array([[23, 26, 23, 33, 33],
       [14, 30, 12, 20, 28],
       [12, 15, 22, 27, 23]])

In [51]:
# GPU Are optimized for matrix operations
# GPU Can have parallel execution
# Nvidia GPU use a cuda programming language 
# numpy is build to run on cpu
# tensorflow and pytorch are implemented for GPU and exposed the api to python
# we use pytorch to move data into gpu 

In [55]:
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

In [58]:
z.grad

tensor(1.)